 socks5 协议笔记

====
* 一字节(1byte)是8bit，也就是8位。4位即可表示一个16进制，所以1byte需要用两个16进制表示。
====

* 第一步，认证

----
参考连接如下:
https://jiajunhuang.com/articles/2019_06_06-socks5.md.html
https://abersheeran.com/articles/Socks5/
----
====
----
+----+----------+----------+
|VER | NMETHODS | METHODS  |
+----+----------+----------+
| 1  |    1     | 1 to 255 |
+----+----------+----------+
----

* VER 是指协议版本，因为是 socks5，所以值是 0x05
* NMETHODS 是指有多少个可以使用的方法，也就是客户端支持的认证方法数量。
如果客户端可以支持两种认证方法例如：`0x00`,`0x01`,`0x02`.那么这个字段的值就是 `0x03`
* METHODS 就是方法值，有多少个方法就有多少个byte
** 0x00 NO AUTHENTICATION REQUIRED 不需要认证
** 0x01 GSSAPI 参考：https://en.wikipedia.org/wiki/GenericSecurityServicesApplicationProgram_Interface
** 0x02 USERNAME/PASSWORD 用户名密码认证。
** 0x03 to 0x7f IANA ASSIGNED 一般不用。INNA保留
** 0x80 to 0xfe RESERVED FOR PRIVATE METHODS 保留作私有用处
** 0xFF NO ACCEPTABLE METHODS 不接受任何方法/没有合适的方法
====

* 第二步，服务器选择认证方式(由服务端策略决定，需要自己实现)
====
----
+----+--------+
|VER | METHOD |
+----+--------+
| 1  |   1    |
+----+--------+
----

* VER与客户端传过来的一致
* METHOD就是服务端选择的认证方式
====

* 第三步，鉴权（根据第二步选择的method来决定这一步是否需要）
====
如果第二步 method为0x00那么就不会执行此逻辑。
如果method 为其他（例如0x02）,那么客户端会发送鉴权数据包。
----
+----+------+----------+------+----------+
|VER | ULEN |  UNAME   | PLEN |  PASSWD  |
+----+------+----------+------+----------+
| 1  |  1   | 1 to 255 |  1   | 1 to 255 |
+----+------+----------+------+----------+
----
如果鉴权成功，status 为0x00,如果鉴权失败则用其他表示(例如0x01)。
----
+----+--------+
|VER | STATUS |
+----+--------+
| 1  |   1    |
+----+--------+
----
====

* 第四步，客户端告知server目标地址
====
----
+----+-----+-------+------+----------+----------+
|VER | CMD |  RSV  | ATYP | DST.ADDR | DST.PORT |
+----+-----+-------+------+----------+----------+
| 1  |  1  | X'00' |  1   | Variable |    2     |
+----+-----+-------+------+----------+----------+
----
* VER 还是版本，取值是 0x05
* CMD 是指要做啥，取值如下：
** CONNECT 0x01 连接
** BIND 0x02 端口监听(也就是在Server上监听一个端口)
** UDP ASSOCIATE 0x03 使用UDP
* RSV 是保留位，值是 0x00
* ATYP 是目标地址类型，有如下取值：
** 0x01 IPv4
** 0x03 域名
** 0x04 IPv6
* DST.ADDR 就是目标地址的值了，如果是IPv4，那么就是4 bytes，如果是IPv6那么就是16 bytes，如果是域名，那么第一个字节代表 接下来有多少个字节是表示目标地址
* DST.PORT 两个字节代表端口号
====
